app-admin/padd: add 3.10.0, drop 3.9.0
Signed-off-by: Andrew Udvare <audvare@gmail.com>

diff --git a/app-admin/padd/files/padd-0001-more-path-fixes.patch b/app-admin/padd/files/padd-0001-more-path-fixes.patch
--- a/app-admin/padd/files/padd-0001-more-path-fixes.patch
+++ b/app-admin/padd/files/padd-0001-more-path-fixes.patch
@@ -1,35 +1,79 @@
-From 849cecb2e4649a253c5ed4ed4e5c5219dac9a1f6 Mon Sep 17 00:00:00 2001
+From 4a9a745f17dc7e6f5da8f1f87d6affcdb1f7fc27 Mon Sep 17 00:00:00 2001
 From: Andrew Udvare <audvare@gmail.com>
-Date: Thu, 16 Dec 2021 09:38:00 -0500
+Date: Sun, 1 Jan 2023 15:10:05 -0500
 Subject: [PATCH] more path fixes
 
 ---
- padd.sh | 10 ++++++----
- 1 file changed, 6 insertions(+), 4 deletions(-)
+ padd.sh | 14 +++++++-------
+ 1 file changed, 7 insertions(+), 7 deletions(-)
 
 diff --git a/padd.sh b/padd.sh
-index 5468f3f..7ca81f6 100755
+index 9a1db47..61bbab9 100755
 --- a/padd.sh
 +++ b/padd.sh
-@@ -25,6 +25,9 @@ cd "$tmpdir/padd_$(id -u)/" > /dev/null || {
-
- ############################################ VARIABLES #############################################
-
-+pihole_version=${XDG_RUNTIME_DIR:-/tmp}/padd.pihole_version
-+padd_pid=${XDG_RUNTIME_DIR:-/tmp}/padd.pid
-+
- # VERSION
- padd_version="v3.7.1"
-
-@@ -1015,7 +1018,7 @@ }
-
+@@ -249,7 +249,7 @@ GetSystemInformation() {
+   elif [ -f /tmp/sysinfo/model ]; then
+     sys_model=$(tr -d '\0' < /tmp/sysinfo/model)
+   elif [ -n "${DOCKER_VERSION}" ]; then
+-    # Docker image. DOCKER_VERSION is read from /etc/pihole/versions
++    # Docker image. DOCKER_VERSION is read from /var/lib/pihole/localversions
+     sys_model="Docker tag ${DOCKER_VERSION}"
+   fi
+ 
+@@ -433,7 +433,7 @@ fi
+ 
+ GetVersionInformation() {
+   # Check if version status has been saved
+-  # all info is sourced from /etc/pihole/versions
++  # all info is sourced from /var/lib/pihole/localversions
+ 
+   out_of_date_flag=false
+ 
+@@ -1148,7 +1148,7 @@ OutputJSON() {
+ 
  StartupRoutine(){
-     # Get config variables
+   # Get config variables
 -  . /etc/pihole/setupVars.conf
 +  . /var/lib/pihole/setupVars.conf
-
+ 
+   # Clear the screen and move cursor to (0,0).
+   # This mimics the 'clear' command.
+@@ -1161,7 +1161,7 @@ StartupRoutine(){
+   moveYOffset
+ 
+   # Get versions information
+-  . /etc/pihole/versions
++  . /var/lib/pihole/localversions
+ 
    if [ "$1" = "pico" ] || [ "$1" = "nano" ] || [ "$1" = "micro" ]; then
-     PrintLogo "$1"
---
-2.35.1
+     moveXOffset; PrintLogo "$1"
+@@ -1275,7 +1275,7 @@ NormalPADD() {
+ 
+     # Get uptime, CPU load, temp, etc. every 5 seconds
+     if [ $((now - LastCheckSystemInformation)) -ge 5 ]; then
+-      . /etc/pihole/setupVars.conf
++      . /var/lib/pihole/setupVars.conf
+       GetSystemInformation
+       LastCheckSystemInformation="${now}"
+     fi
+@@ -1300,7 +1300,7 @@ NormalPADD() {
+ 
+     # Get Pi-hole components version information every 30 seconds
+     if [ $((now - LastCheckVersionInformation)) -ge 30 ]; then
+-      . /etc/pihole/versions
++      . /var/lib/pihole/localversions
+       GetVersionInformation
+       LastCheckVersionInformation="${now}"
+     fi
+@@ -1375,7 +1375,7 @@ main(){
+ 
+     # If setupVars.conf is not present, then PADD is not running on a Pi-hole
+     # and we are not able to start as StartupRoutine() will fail below
+-    if [ ! -f /etc/pihole/setupVars.conf ]; then
++    if [ ! -f /var/lib/pihole/setupVars.conf ]; then
+       printf "%b" "${check_box_bad} Error!\n    PADD only works in conjunction with Pi-hole!\n"
+       exit 1
+     fi
+-- 
+2.39.0
 
